AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway HTTP API for johns_ai_project_backend

Parameters:
  BackendUrl:
    Type: String
    Description: Backend server URL (e.g., http://your-alb-123456789.us-east-1.elb.amazonaws.com:8080)
    Default: http://localhost:8080
  
  StageName:
    Type: String
    Description: API Gateway stage name
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
  
  Environment:
    Type: String
    Description: Environment name
    Default: production
    AllowedValues:
      - development
      - staging
      - production

Resources:
  # API Gateway HTTP API
  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub johns-ai-project-api-${Environment}
      ProtocolType: HTTP
      Description: API Gateway for Mental Health Counselling Client Management System
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
        AllowHeaders:
          - "*"
        MaxAge: 300
      Tags:
        - Key: Project
          Value: johns_ai_project_backend
        - Key: Environment
          Value: !Ref Environment

  # Default stage
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGateway
      StageName: !Ref StageName
      AutoDeploy: true
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50
        DetailedMetricsEnabled: true
      AccessLogSettings:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: |
          {
            "requestId": "$context.requestId",
            "ip": "$context.identity.sourceIp",
            "requestTime": "$context.requestTime",
            "httpMethod": "$context.httpMethod",
            "routeKey": "$context.routeKey",
            "status": "$context.status",
            "protocol": "$context.protocol",
            "responseLength": "$context.responseLength"
          }

  # CloudWatch Log Group for API Gateway
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${ApiGateway}
      RetentionInDays: 7

  # Integration with backend server
  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGateway
      IntegrationType: HTTP_PROXY
      IntegrationUri: !Ref BackendUrl
      IntegrationMethod: ANY
      PayloadFormatVersion: "1.0"
      ConnectionType: INTERNET
      TimeoutInMillis: 30000

  # Health check route
  HealthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /health
      Target: !Sub integrations/${ApiIntegration}

  # Get all clients route
  ClientsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/clients
      Target: !Sub integrations/${ApiIntegration}

  # Get active clients route
  ActiveClientsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/clients/active
      Target: !Sub integrations/${ApiIntegration}

  # Get inactive clients route
  InactiveClientsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/clients/inactive
      Target: !Sub integrations/${ApiIntegration}

  # Get client by ID route (with path parameter)
  ClientByIdRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: GET /api/clients/{id}
      Target: !Sub integrations/${ApiIntegration}

  # Catch-all route for any other paths (optional)
  CatchAllRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGateway
      RouteKey: $default
      Target: !Sub integrations/${ApiIntegration}

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint
  
  ApiId:
    Description: API Gateway ID
    Value: !Ref ApiGateway
    Export:
      Name: !Sub ${AWS::StackName}-ApiId

