AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for johns_ai_project_backend

Resources:
  ClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: clients
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: johns_ai_project_backend
        - Key: Environment
          Value: production

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: johns_ai_project_backend
        - Key: Environment
          Value: production

Outputs:
  ClientsTableName:
    Description: Name of the Clients DynamoDB table
    Value: !Ref ClientsTable
    Export:
      Name: !Sub ${AWS::StackName}-clients-table

  UsersTableName:
    Description: Name of the Users DynamoDB table
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${AWS::StackName}-users-table
